"""
YOLO Model Trainer
==================
Trains a YOLOv8n model to detect "[Lv.6000] Velik" labels on screen.

Prerequisites:
  pip install ultralytics

Dataset structure (export from Roboflow as "YOLOv8" format, extract here):
  yolo_data/
    images/
      train/   <- training images (.png)
      val/     <- validation images (.png)
    labels/
      train/   <- YOLO .txt annotations
      val/
    data.yaml  <- generated by Roboflow - edit class name if needed

Usage:
  python train_yolo.py

Output:
  runs/detect/boss_detector/weights/best.pt
  -> copy that file to:  models/boss_detector.pt
"""

import os
import shutil
from pathlib import Path

DATA_YAML   = "yolo_data/data.yaml"
OUTPUT_NAME = "boss_detector"
EPOCHS      = 50
IMG_SIZE    = 640
BATCH       = 8    # lower if GPU OOM; raise to 16 if >4 GB VRAM free


def main():
    try:
        from ultralytics import YOLO
    except ImportError:
        print("ERROR: ultralytics not installed.")
        print("Run:  pip install ultralytics")
        return

    if not os.path.isfile(DATA_YAML):
        print(f"ERROR: {DATA_YAML} not found.")
        print("You need to export your Roboflow dataset and place it in yolo_data/")
        return

    print("=" * 55)
    print(f"  Training YOLOv8n - {EPOCHS} epochs, img {IMG_SIZE}px")
    print(f"  Dataset: {os.path.abspath(DATA_YAML)}")
    print("=" * 55)

    model = YOLO("yolov8n.pt")   # downloads ~6 MB on first run

    results = model.train(
        data     = DATA_YAML,
        epochs   = EPOCHS,
        imgsz    = IMG_SIZE,
        batch    = BATCH,
        name     = OUTPUT_NAME,
        patience = 15,           # early stop if no improvement
        device   = 0,            # GPU 0; "cpu" if no GPU
        workers  = 2,
        verbose  = True,
    )

    # Copy best weight to expected location
    best = Path(f"runs/detect/{OUTPUT_NAME}/weights/best.pt")
    if best.exists():
        os.makedirs("models", exist_ok=True)
        shutil.copy(best, "models/boss_detector.pt")
        print("\n" + "=" * 55)
        print("  Training complete!")
        print("  Model saved to: models/boss_detector.pt")
        print("  The bot will automatically use it next time main.py runs.")
        print("=" * 55)
    else:
        print("WARNING: best.pt not found at expected location.")
        print(f"Look in: {best.parent}")


if __name__ == "__main__":
    main()
